resolver: lts-18.16

packages:
- '.'

flags:
  # This significantly speeds up CI builds, and we don't really need Pandoc for
  # this website.
  hakyll:
    usePandoc: false

extra-deps:
- 'hakyll-4.15.1.0'

nix:
  packages:
  - 'zlib'
